# Generated by Django 4.2.3 on 2023-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='fees_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='student',
            name='student_roll',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
