# Generated by Django 4.2.3 on 2023-07-12 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0002_rename_name_student_student_name_student_fees_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
