# Generated by Django 4.2.3 on 2023-07-12 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0005_alter_student_april_fees_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStudentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=64)),
                ('student_roll', models.CharField(max_length=64, null=True)),
                ('student_class', models.IntegerField(default=8)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('fees_amount', models.IntegerField(default=0)),
                ('school_name', models.CharField(max_length=64, null=True)),
                ('january_fees_date', models.DateField(blank=True, null=True)),
                ('february_fees_date', models.DateField(blank=True, null=True)),
                ('march_fees_date', models.DateField(blank=True, null=True)),
                ('april_fees_date', models.DateField(blank=True, null=True)),
                ('may_fees_date', models.DateField(blank=True, null=True)),
                ('june_fees_date', models.DateField(blank=True, null=True)),
                ('july_fees_date', models.DateField(blank=True, null=True)),
                ('august_fees_date', models.DateField(blank=True, null=True)),
                ('september_fees_date', models.DateField(blank=True, null=True)),
                ('october_fees_date', models.DateField(blank=True, null=True)),
                ('november_fees_date', models.DateField(blank=True, null=True)),
                ('december_fees_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.CreateModel(
            name='StudentClassEight',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.CreateModel(
            name='StudentClassNine',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
    ]
