# Generated by Django 4.2.3 on 2023-07-12 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0006_basestudentmodel_delete_student_studentclasseight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestudentmodel',
            name='student_class',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
