# Generated by Django 4.2.3 on 2023-07-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0007_alter_basestudentmodel_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudenClassElevenScience',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.CreateModel(
            name='StudentClassElevenCommerce',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.CreateModel(
            name='StudentClassTen',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.CreateModel(
            name='StudentClassTwelveCommerce',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.CreateModel(
            name='StudentClassTwelveScience',
            fields=[
                ('basestudentmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feesmanagement.basestudentmodel')),
            ],
            bases=('feesmanagement.basestudentmodel',),
        ),
        migrations.AddField(
            model_name='basestudentmodel',
            name='mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basestudentmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='basestudentmodel',
            name='student_roll',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
