# Generated by Django 4.2.3 on 2023-07-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0008_studenclasselevenscience_studentclasselevencommerce_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basestudentmodel',
            old_name='mobile_number',
            new_name='student_mobile_number',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='april_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='august_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='december_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='february_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='january_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='july_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='june_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='march_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='may_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='november_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='october_fees_date',
        ),
        migrations.RemoveField(
            model_name='basestudentmodel',
            name='september_fees_date',
        ),
        migrations.AddField(
            model_name='basestudentmodel',
            name='guardian_mobile_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='basestudentmodel',
            name='subjects',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='march_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasseight',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='march_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassnine',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='march_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclassten',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='april_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='august_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='february_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='january_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='july_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='june_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='may_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='november_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='october_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='september_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
