# Generated by Django 4.2.3 on 2023-07-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0009_rename_mobile_number_basestudentmodel_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=10, null=True)),
                ('standard', models.IntegerField()),
                ('name', models.CharField(max_length=40, null=True)),
                ('subjects', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studenclasselevenscience',
            options={'verbose_name': 'Class Eleven Science', 'verbose_name_plural': 'Class Eleven Science Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasseight',
            options={'verbose_name': 'Class Eight', 'verbose_name_plural': 'Class Eight Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasselevencommerce',
            options={'verbose_name': 'Class Eleven Commerce', 'verbose_name_plural': 'Class Eleven Commerce Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclassnine',
            options={'verbose_name': 'Class Nine', 'verbose_name_plural': 'Class Nine Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclassten',
            options={'verbose_name': 'Class Ten', 'verbose_name_plural': 'Class Ten Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasstwelvecommerce',
            options={'verbose_name': 'Class Twelve Commerce', 'verbose_name_plural': 'Class Twelve Commerce Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasstwelvescience',
            options={'verbose_name': 'Class Twelve Science', 'verbose_name_plural': 'Class Twelve Science Records'},
        ),
    ]
