# Generated by Django 4.0.3 on 2023-08-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0009_rename_mobile_number_basestudentmodel_student_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenclasselevenscience',
            options={'verbose_name': 'Class Eleven Science', 'verbose_name_plural': 'Class Eleven Science Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasseight',
            options={'verbose_name': 'Class Eight', 'verbose_name_plural': 'Class Eight Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasselevencommerce',
            options={'verbose_name': 'Class Eleven Commerce', 'verbose_name_plural': 'Class Eleven Commerce Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclassnine',
            options={'verbose_name': 'Class Nine', 'verbose_name_plural': 'Class Nine Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclassten',
            options={'verbose_name': 'Class Ten', 'verbose_name_plural': 'Class Ten Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasstwelvecommerce',
            options={'verbose_name': 'Class Twelve Commerce', 'verbose_name_plural': 'Class Twelve Commerce Records'},
        ),
        migrations.AlterModelOptions(
            name='studentclasstwelvescience',
            options={'verbose_name': 'Class Twelve Science', 'verbose_name_plural': 'Class Twelve Science Records'},
        ),
    ]
