# Generated by Django 4.0.3 on 2023-08-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0010_alter_studenclasselevenscience_options_and_more'),
        ('feesmanagement', '0010_feesrecord_alter_studenclasselevenscience_options_and_more'),
    ]

    operations = [
    ]
