# Generated by Django 4.0.3 on 2023-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0011_merge_20230808_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenclasselevenscience',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasselevencommerce',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvecommerce',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentclasstwelvescience',
            name='december_fees_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
