# Generated by Django 4.0.3 on 2023-08-13 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feesmanagement', '0012_studenclasselevenscience_december_fees_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestudentmodel',
            name='student_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
